format:
  html:
    self-contained: true
  pptx:
    toc: false
    slide-level: 2

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Slides"
        href: slides.qmd
