project:
  type: document
  output-dir: .

format:
  pptx:
    toc: true
    slide-level: 2

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Slides"
        href: slides.qmd
