on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: '4.2.0'

      # - name: Install R Dependencies
      #   uses: r-lib/actions/setup-renv@v2
      #   with:
      #     cache-version: 1

      - name: Debug - List repository contents
        run: ls -l

      - name: Render and Publish
        run: quarto render slides.qmd --to html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "quarto-github-actions-publish@example.com"
          git config --global user.name "Quarto GHA Workflow Runner"
          git add slides.html
          git commit -m "Add rendered slides.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
